### ISSUE TITLE
[zsh] Would be great to have 5-8 recent commands listed already

### ISSUE THREAD

**Issue by hamxabaig** [siddharthkp/historie#2]
When we type `historie` in the command line. It'd be great to show list of recent commands say like 5-8 of them. Right now it just shows me to search, leaving me to additional key strokes. ;)

**Comment by siddharthkp** [comment]
That's how it works on mac 😄 

Which OS are you on?

**Comment by hamxabaig** [comment]
haha, I'm on mac too. I'm using zsh in terminal.

**Comment by siddharthkp** [comment]
Interesting 🤔

Which terminal are you using?

**Comment by hamxabaig** [comment]
@siddharthkp zsh.

**Comment by hamxabaig** [comment]
Thought it'll help.

<img width="1183" alt="screen shot 2017-07-11 at 3 26 52 pm" src="https://user-images.githubusercontent.com/12872177/28064276-6ae635f0-664d-11e7-88b1-411a218582ff.png">

**Comment by siddharthkp** [comment]
Hmm,

`historie` uses [sindresorhus/shell-history](https://github.com/sindresorhus/shell-history)

Can you check if that works with zsh?

If not, I'll try to implement it.

**Comment by hamxabaig** [comment]
@siddharthkp `shell-history` gives me all of the commands that were typed. Its working.

**Comment by siddharthkp** [comment]
I just tried with zsh, working for me 🙈 

Can you help me debug this?

**Comment by hamxabaig** [comment]
Umm strange. Yeah sure, would love to help.

**Comment by hamxabaig** [comment]
After typing `historie`, it gives me nothing (as in screenshot above). But when i try to filter by typing some command name. It actually gives me the list. o.O

**Comment by siddharthkp** [comment]
Here's the line for the starting case: 

https://github.com/siddharthkp/historie/blob/master/history.js#L15

**Comment by hamxabaig** [comment]
@siddharthkp Sure, I'll check this. Forked 🎉

**Comment by willhoney7** [comment]
FWIW, I'm using zsh (with ohmyz.sh) and it works properly. Not sure what the cause would be for your case.

**Comment by hamxabaig** [comment]
@siddharthkp I checked and problem was that `hint` was empty when typing `historie`. So filtering commands with empty `hint` was returning empty `choices`. I added a check when `hint` is empty then i just resolve it with recent 8 commands.
