### ISSUE TITLE
[windows] Just installed it, no history?

### ISSUE THREAD

**Issue by spences10** [siddharthkp/historie#3]
Windows user checking in 👋 

Installed `historie` started the `historie` command and arrow up and down and search have no results

I'm using cmder and tried in the VSCode terminal too, no dice

**Comment by siddharthkp** [comment]
Hey, `historie` uses [sindresorhus/shell-history](https://github.com/sindresorhus/shell-history)

Can you check if that supports windows. 

If you can tell me what's the path for your history file, I might be able to raise a pull request to `shell-history`

**Comment by spences10** [comment]
:cry: 
![image](https://user-images.githubusercontent.com/234708/28063908-acdf1fa8-662a-11e7-9638-26c777465825.png)

So in cmder or powershell even you can cycle through your last commands??

Happy for you to close this @siddharthkp

**Comment by siddharthkp** [comment]
That's a bummer 😢

**Comment by siddharthkp** [comment]
> So in cmder or powershell even you can cycle through your last commands??

Do cmder and powershell cache their own versions?

**Comment by spences10** [comment]
>Do cmder and powershell cache their own versions?

I guess, I'm using windows 10 it may be some of the features of adding cmder [conemu] I have just tried on this wondows 7 machine in git bash and powershell and no history

I'll have to have a look when I get home tonight :+1:
